/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>
getContractFactory(name: 'PartioV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PartioV2__factory>
getContractFactory(name: 'PartioVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PartioVault__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'Partio', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Partio__factory>

  getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>
getContractAt(name: 'PartioV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PartioV2>
getContractAt(name: 'PartioVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PartioVault>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'Partio', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Partio>

  deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'PartioV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PartioV2>
deployContract(name: 'PartioVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PartioVault>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Partio', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Partio>

  deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>
deployContract(name: 'PartioV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PartioV2>
deployContract(name: 'PartioVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PartioVault>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Partio', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Partio>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  