/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PartioV2Interface extends Interface {
    getFunction(nameOrSignature: "createPayment" | "getPaymentVault" | "paymentCount" | "payments" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createPayment', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPaymentVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paymentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'payments', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createPayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPaymentVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace PaymentCreatedEvent {
      export type InputTuple = [paymentId: BigNumberish, owner: AddressLike, vault: AddressLike];
      export type OutputTuple = [paymentId: bigint, owner: string, vault: string];
      export interface OutputObject {paymentId: bigint, owner: string, vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PartioV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): PartioV2;
    waitForDeployment(): Promise<this>;

    interface: PartioV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createPayment: TypedContractMethod<
      [],
      [[bigint, string] & {paymentId: bigint, vault: string }],
      'nonpayable'
    >
    

    
    getPaymentVault: TypedContractMethod<
      [paymentId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    paymentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    payments: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createPayment'): TypedContractMethod<
      [],
      [[bigint, string] & {paymentId: bigint, vault: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPaymentVault'): TypedContractMethod<
      [paymentId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'payments'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentCreated'): TypedContractEvent<PaymentCreatedEvent.InputTuple, PaymentCreatedEvent.OutputTuple, PaymentCreatedEvent.OutputObject>;

    filters: {
      
      'PaymentCreated(uint256,address,address)': TypedContractEvent<PaymentCreatedEvent.InputTuple, PaymentCreatedEvent.OutputTuple, PaymentCreatedEvent.OutputObject>;
      PaymentCreated: TypedContractEvent<PaymentCreatedEvent.InputTuple, PaymentCreatedEvent.OutputTuple, PaymentCreatedEvent.OutputObject>;
    
    };
  }