/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PartioVaultInterface extends Interface {
    getFunction(nameOrSignature: "balance" | "execute" | "executed" | "owner" | "refund" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentExecuted" | "Refunded"): EventFragment;

    encodeFunctionData(functionFragment: 'balance', values?: undefined): string;
encodeFunctionData(functionFragment: 'execute', values: [AddressLike[], BigNumberish[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'executed', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'balance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace PaymentExecutedEvent {
      export type InputTuple = [owner: AddressLike, totalAmount: BigNumberish, recipientCount: BigNumberish];
      export type OutputTuple = [owner: string, totalAmount: bigint, recipientCount: bigint];
      export interface OutputObject {owner: string, totalAmount: bigint, recipientCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PartioVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): PartioVault;
    waitForDeployment(): Promise<this>;

    interface: PartioVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    execute: TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentExecuted'): TypedContractEvent<PaymentExecutedEvent.InputTuple, PaymentExecutedEvent.OutputTuple, PaymentExecutedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;

    filters: {
      
      'PaymentExecuted(address,uint256,uint256)': TypedContractEvent<PaymentExecutedEvent.InputTuple, PaymentExecutedEvent.OutputTuple, PaymentExecutedEvent.OutputObject>;
      PaymentExecuted: TypedContractEvent<PaymentExecutedEvent.InputTuple, PaymentExecutedEvent.OutputTuple, PaymentExecutedEvent.OutputObject>;
    

      'Refunded(address,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    
    };
  }