/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PartioInterface extends Interface {
    getFunction(nameOrSignature: "partition" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentPartitioned" | "PaymentSent"): EventFragment;

    encodeFunctionData(functionFragment: 'partition', values: [AddressLike[], BigNumberish[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'partition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace PaymentPartitionedEvent {
      export type InputTuple = [sender: AddressLike, totalAmount: BigNumberish, recipientCount: BigNumberish];
      export type OutputTuple = [sender: string, totalAmount: bigint, recipientCount: bigint];
      export interface OutputObject {sender: string, totalAmount: bigint, recipientCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentSentEvent {
      export type InputTuple = [sender: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, recipient: string, amount: bigint];
      export interface OutputObject {sender: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Partio extends BaseContract {
    
    connect(runner?: ContractRunner | null): Partio;
    waitForDeployment(): Promise<this>;

    interface: PartioInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    partition: TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'partition'): TypedContractMethod<
      [recipients: AddressLike[], amounts: BigNumberish[], totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentPartitioned'): TypedContractEvent<PaymentPartitionedEvent.InputTuple, PaymentPartitionedEvent.OutputTuple, PaymentPartitionedEvent.OutputObject>;
getEvent(key: 'PaymentSent'): TypedContractEvent<PaymentSentEvent.InputTuple, PaymentSentEvent.OutputTuple, PaymentSentEvent.OutputObject>;

    filters: {
      
      'PaymentPartitioned(address,uint256,uint256)': TypedContractEvent<PaymentPartitionedEvent.InputTuple, PaymentPartitionedEvent.OutputTuple, PaymentPartitionedEvent.OutputObject>;
      PaymentPartitioned: TypedContractEvent<PaymentPartitionedEvent.InputTuple, PaymentPartitionedEvent.OutputTuple, PaymentPartitionedEvent.OutputObject>;
    

      'PaymentSent(address,address,uint256)': TypedContractEvent<PaymentSentEvent.InputTuple, PaymentSentEvent.OutputTuple, PaymentSentEvent.OutputObject>;
      PaymentSent: TypedContractEvent<PaymentSentEvent.InputTuple, PaymentSentEvent.OutputTuple, PaymentSentEvent.OutputObject>;
    
    };
  }